service:
  db:
    container_name: ${PROJECT_NAME:-default}-postgres-container
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      PGPASSWORD: ${PGPASSWORD:-password123}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      TZ: "Asia/Tokyo"
    ports:
      - 5432:5432
#    volumes:
#      - ./.docker/postgres/data:/var/lib/postgresql/data
