server:
  shutdown: graceful

spring:
  jpa:
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true
  threads:
    virtual:
      enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
logging:
  level:
    root: warn
    web: info
