version: "3"
services:
  app:
    image: openjdk:21
    ports:
      - "80:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: ./gradlew -daemon :spring-modulith-application:bootRun
#    environment:
#      DATASOURCE: jdbc:mysql://db:3306/sample