spring:
  application:
    name: modulith-service
#Datasource Configuration
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

#JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
